apiVersion: apps/v1
kind: Deployment
metadata:
  name: ak-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ak-nginx
  template:
    metadata:
      labels:
        app: ak-nginx
    spec:
      containers:
      - name: ak-nginx
        image: nginx:1.25.0
        ports:
        - containerPort: 80
 #     imagePullSecrets:
  #    - name: harbor-secret

