apiVersion: apps/v1
kind: Deployment
metadata:
  name: ak-nginx
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ak-nginx
  template:
    metadata:
      labels:
        app: ak-nginx
    spec:
      containers:
      - name: ak-nginx
        image: 329599621384.dkr.ecr.ap-south-1.amazonaws.com/demorepo1:nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
