apiVersion: apps/v1
kind: Deployment
metadata:
  name: ak-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ak-nginx
  template:
    metadata:
      labels:
        app: ak-nginx
    spec:
      containers:
      - name: ak-nginx
        image: www.magicbus.tech/argocd/ak-nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
